### ISSUE TITLE
Immagini in ARM

### ISSUE THREAD

**Issue by andreapoli** [link-it/govway-docker#13]
**Necessità:**
Immagini Docker per arm64

**Soluzione:**
Creare immagine che sia multi arch, quindi sia per arm64 che per amd64

**Comment by francescor** [comment]
buongiorno 

come dicevamo in https://github.com/link-it/govway/issues/178 

non avere l'immagine per arm64 ci blocca la migrazione della nostra infrastruttura verso ARM (abbiamo diversi servizi in produzione con govway, grazie!): per noi sono gravi svantaggi in termini di costi (ma pure prestazioni), senza dimenticare le spinte green comprensibili.  Siamo a dipo eventualmente per testare la versione arm in ambiente di qa e poi produzione.

**Comment by francescor** [comment]
novità qui? o previsione di quando sarà possibile?

**Comment by nicolabeghin** [comment]
Se utili nel frattempo, unofficial arm64 builds usate senza problemi in produzione

https://hub.docker.com/r/nicolabeghin/govway

**Comment by francescor** [comment]
grazie @nicolabeghin !

(noi ora usiamo `linkitaly/govway:3.3.14_standalone`, ed ahinoi vedo che questa `_standalone` non c'è nel tuo docker hub :(

**Comment by andreapoli** [comment]
Il lavoro sta procedendo nel branch [issue_13](https://github.com/link-it/govway-docker/tree/issuse_13)

Abbiamo iniziato a pubblicare delle immagini in multipiattaforma nel repository di sviluppo https://hub.docker.com/r/linkitaly/govway-dev/tags per consentire dei test.

@francescor se vuoi provarla c'è anche la versione [master_standalone](https://hub.docker.com/layers/linkitaly/govway-dev/master_standalone/images/sha256-9be06740e484e650ff87dbb06466553b62b4195a1b76f8aa0776fd44ee58d9c6)

**Comment by andreapoli** [comment]
@francescor le versioni snapshot prodotte nell'ambiente di [continuous integration](https://jenkins.link.it/govway/job/GovWay/) vengono adesso depositate come immagini multipiattaforma.

- [master_standalone](https://hub.docker.com/layers/linkitaly/govway/master_standalone/images/sha256-ca64120f6dd6348b3565e397b03d523414911bcc373f275092273a7f5078afd5)
- [master_oracle](https://hub.docker.com/layers/linkitaly/govway/master_oracle/images/sha256-6fd09e02f7ca450b0412d09f984d65c1d0836000760a1b4a15a6004e513de91b)
- [master_postgresql](https://hub.docker.com/layers/linkitaly/govway/master_postgres/images/sha256-c6244121a2e040adf6d621804c886b650bec0c8f8b34650b77f8372d21fd0cea)

Le immagini relative alla prossima versione di GovWay saranno rilasciate in multipiattaforma.

**Comment by francescor** [comment]
yes, Multiarch, great!

```
docker manifest inspect linkitaly/govway:master_standalone | grep -i arch 
            "architecture": "amd64",
            "architecture": "arm64",
```

Ho provato ora:

se passo da 
` image: linkitaly/govway:3.3.14_standalone  # manca arm`
a 
`image: linkitaly/govway:master_standalone`

Vedo: 

```
govway-qa_server.1.ky7b9jbhtdo2@boat-worker-ecbf    | INFO: Scripts SQL inizializzati.
govway-qa_server.1.ky7b9jbhtdo2@boat-worker-ecbf    | INFO: Readyness base dati RUN ... riprovo
govway-qa_server.1.ky7b9jbhtdo2@boat-worker-ecbf    | INFO: Readyness base dati RUN ... riprovo
govway-qa_server.1.ky7b9jbhtdo2@boat-worker-ecbf    | INFO: Readyness base dati RUN ... riprovo
govway-qa_server.1.ky7b9jbhtdo2@boat-worker-ecbf    | INFO: Readyness base dati RUN ... riprovo
govway-qa_server.1.ky7b9jbhtdo2@boat-worker-ecbf    | INFO: Readyness base dati RUN ... riprovo
govway-qa_server.1.ky7b9jbhtdo2@boat-worker-ecbf    | FATAL: Readyness base dati RUN ... Base dati NON disponibile dopo 10 secondi
govway-qa_server.1.ky7b9jbhtdo2@boat-worker-ecbf    | FATAL: Database non inizializzato.
```

anzichè 

```
govway-qa_server.1.71jyylu40o0o@boat-worker-ecbf    | INFO: Scripts SQL inizializzati.
govway-qa_server.1.71jyylu40o0o@boat-worker-ecbf    | 
govway-qa_server.1.71jyylu40o0o@boat-worker-ecbf    | INFO: Readyness base dati RUN ... inizializzazione completata.
govway-qa_server.1.71jyylu40o0o@boat-worker-ecbf    | 
govway-qa_server.1.71jyylu40o0o@boat-worker-ecbf    | INFO: Readyness base dati CONF ... inizializzazione completata.
```

L'errore esce a prescindere da ARM, x86, quindi qui mi sa che devo impostare qualcosa passando dalla `3.3.14_standalone` alla `master_standalone`

**Comment by marklar79** [comment]
Ciao @francescor 

Puoi darci delle informazioni aggiuntive su come avvii il container? A linea di comando o tramite docker compose? E quali variabili d'ambiente hai specificato?

Grazie

**Comment by francescor** [comment]
usiamo docker swarm


qui l'intero file di stack, attualmente funzionante (ho solo rinominato dominio con `mydomain.com`): 



```
version: "3.9"

networks:
  traefik-mix:
    external: true
    name: traefik-mix
  internal:

services:

  server:
    #https://hub.docker.com/r/linkitaly/govway
    image: linkitaly/govway:3.3.14_standalone  # manca arm
    # immagine arm, non ufficiale, in https://github.com/link-it/govway-docker/issues/13#issuecomment-2510231993
    # francesco prova, qui in qa, la versione ARM (multiarch)
    # image: linkitaly/govway:master_standalone  # multiarch
    # image: linkitaly/govway:master_standalone_linux_arm64_v8
    # image: linkitaly/govway:master_standalone_linux_amd64
    volumes:
      - /srv/data/govway-qa/etc:/etc/govway
      - /srv/data/govway-qa/logs:/var/log/govway
      - /srv/data/govway-qa/hsqldb:/opt/hsqldb-2.7.1/hsqldb/database
    networks:
      - traefik-mix
      - internal
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.platform.arch == x86_64
          # - node.platform.arch == aarch64
          - engine.labels.jobs-type == stateless
      update_config:
        order: stop-first
        delay: 10s
      restart_policy:
        condition: any
        max_attempts: 1
        window: 120s
      resources:
        reservations:
          memory: 2G
        limits:
          memory: 3G
      labels:
        diun.watch_repo: 'true'
        traefik.enable: 'true'
        traefik.docker.network: traefik-mix

        traefik.http.services.govway-qa-out.loadbalancer.server.port: 8080
        traefik.http.routers.govway-qa-out.service: govway-qa-out
        traefik.http.routers.govway-qa-out.rule: Host(`govway-qa-out.mydomain.com`)
        traefik.http.routers.govway-qa-out.tls: 'true'
        traefik.http.routers.govway-qa-out.tls.certresolver: mydnschallenge
        traefik.http.routers.govway-qa-out.middlewares: goodheaders

        traefik.http.services.govway-qa-in.loadbalancer.server.port: 8081
        traefik.http.routers.govway-qa-in.service: govway-qa-in
        traefik.http.routers.govway-qa-in.rule: Host(`govway-qa-in.boat.mydomain.com`)
        traefik.http.routers.govway-qa-in.tls: 'true'
        traefik.http.routers.govway-qa-in.tls.certresolver: mydnschallenge
        traefik.http.routers.govway-qa-in.middlewares: goodheaders

        traefik.http.services.govway-qa-admin.loadbalancer.server.port: 8082
        traefik.http.routers.govway-qa-admin.service: govway-qa-admin
        traefik.http.routers.govway-qa-admin.rule: 'Host(`govway-qa.mydomain.com`)'
        traefik.http.routers.govway-qa-admin.tls: 'true'
        traefik.http.routers.govway-qa-admin.tls.certresolver: mydnschallenge
        traefik.http.routers.govway-qa-admin.middlewares: goodheaders


    environment:
      TZ: Europe/Rome
      GOVWAY_DEFAULT_ENTITY_NAME: Ente
      # abilitando la variabile 'GOVWAY_POP_DB_SKIP' non verra effettuata l'inizializzazione della base dati.
      GOVWAY_POP_DB_SKIP: 'false'
```

Gli errori compaiono cambiando `image: `  con quelle commentate (ed adeguando `node.platform.arch`)
